name: Linter-Status

on:
  push: 
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  run-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Install dependences
        run: |
          gem install bundler
          bundle install

      - name: Run Rubocop
        run: |
          make lint
